packages:
  - .

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - canvas
  - esbuild
  - msw
  - protobufjs

patchedDependencies:
  prebuild-install@7.1.3: patches/prebuild-install@7.1.3.patch
